/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/robot/rieman_ws/src/biotac_driver/biotac_sensors/msg/BioTacTime.msg
 *
 */


#ifndef BIOTAC_SENSORS_MESSAGE_BIOTACTIME_H
#define BIOTAC_SENSORS_MESSAGE_BIOTACTIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace biotac_sensors
{
template <class ContainerAllocator>
struct BioTacTime_
{
  typedef BioTacTime_<ContainerAllocator> Type;

  BioTacTime_()
    : frame_start_time()
    , frame_end_time()
    , tdc_ns_offset(0)
    , tac_ns_offset(0)
    , pdc_ns_offset(0)
    , pac_ns_offset()
    , electrode_ns_offset()  {
      pac_ns_offset.assign(0);

      electrode_ns_offset.assign(0);
  }
  BioTacTime_(const ContainerAllocator& _alloc)
    : frame_start_time()
    , frame_end_time()
    , tdc_ns_offset(0)
    , tac_ns_offset(0)
    , pdc_ns_offset(0)
    , pac_ns_offset()
    , electrode_ns_offset()  {
      pac_ns_offset.assign(0);

      electrode_ns_offset.assign(0);
  }



   typedef ros::Time _frame_start_time_type;
  _frame_start_time_type frame_start_time;

   typedef ros::Time _frame_end_time_type;
  _frame_end_time_type frame_end_time;

   typedef uint32_t _tdc_ns_offset_type;
  _tdc_ns_offset_type tdc_ns_offset;

   typedef uint32_t _tac_ns_offset_type;
  _tac_ns_offset_type tac_ns_offset;

   typedef uint32_t _pdc_ns_offset_type;
  _pdc_ns_offset_type pdc_ns_offset;

   typedef boost::array<uint32_t, 22>  _pac_ns_offset_type;
  _pac_ns_offset_type pac_ns_offset;

   typedef boost::array<uint32_t, 19>  _electrode_ns_offset_type;
  _electrode_ns_offset_type electrode_ns_offset;




  typedef boost::shared_ptr< ::biotac_sensors::BioTacTime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::biotac_sensors::BioTacTime_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct BioTacTime_

typedef ::biotac_sensors::BioTacTime_<std::allocator<void> > BioTacTime;

typedef boost::shared_ptr< ::biotac_sensors::BioTacTime > BioTacTimePtr;
typedef boost::shared_ptr< ::biotac_sensors::BioTacTime const> BioTacTimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::biotac_sensors::BioTacTime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::biotac_sensors::BioTacTime_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace biotac_sensors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'biotac_sensors': ['/home/robot/rieman_ws/src/biotac_driver/biotac_sensors/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::biotac_sensors::BioTacTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::biotac_sensors::BioTacTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::biotac_sensors::BioTacTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::biotac_sensors::BioTacTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::biotac_sensors::BioTacTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::biotac_sensors::BioTacTime_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::biotac_sensors::BioTacTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8d8b5e140ed0958883d472dc8acc1dc";
  }

  static const char* value(const ::biotac_sensors::BioTacTime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8d8b5e140ed0958ULL;
  static const uint64_t static_value2 = 0x883d472dc8acc1dcULL;
};

template<class ContainerAllocator>
struct DataType< ::biotac_sensors::BioTacTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "biotac_sensors/BioTacTime";
  }

  static const char* value(const ::biotac_sensors::BioTacTime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::biotac_sensors::BioTacTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time frame_start_time\n\
time frame_end_time\n\
uint32 tdc_ns_offset\n\
uint32 tac_ns_offset\n\
uint32 pdc_ns_offset\n\
uint32[22] pac_ns_offset\n\
uint32[19] electrode_ns_offset\n\
";
  }

  static const char* value(const ::biotac_sensors::BioTacTime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::biotac_sensors::BioTacTime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_start_time);
      stream.next(m.frame_end_time);
      stream.next(m.tdc_ns_offset);
      stream.next(m.tac_ns_offset);
      stream.next(m.pdc_ns_offset);
      stream.next(m.pac_ns_offset);
      stream.next(m.electrode_ns_offset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BioTacTime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::biotac_sensors::BioTacTime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::biotac_sensors::BioTacTime_<ContainerAllocator>& v)
  {
    s << indent << "frame_start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.frame_start_time);
    s << indent << "frame_end_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.frame_end_time);
    s << indent << "tdc_ns_offset: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tdc_ns_offset);
    s << indent << "tac_ns_offset: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tac_ns_offset);
    s << indent << "pdc_ns_offset: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pdc_ns_offset);
    s << indent << "pac_ns_offset[]" << std::endl;
    for (size_t i = 0; i < v.pac_ns_offset.size(); ++i)
    {
      s << indent << "  pac_ns_offset[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.pac_ns_offset[i]);
    }
    s << indent << "electrode_ns_offset[]" << std::endl;
    for (size_t i = 0; i < v.electrode_ns_offset.size(); ++i)
    {
      s << indent << "  electrode_ns_offset[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.electrode_ns_offset[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOTAC_SENSORS_MESSAGE_BIOTACTIME_H
