/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/robot/catkin_ws/src/wam_common/wam_msgs/srv/SpecialService.srv
 *
 */


#ifndef WAM_MSGS_MESSAGE_SPECIALSERVICE_H
#define WAM_MSGS_MESSAGE_SPECIALSERVICE_H

#include <ros/service_traits.h>


#include <wam_msgs/SpecialServiceRequest.h>
#include <wam_msgs/SpecialServiceResponse.h>


namespace wam_msgs
{

struct SpecialService
{

typedef SpecialServiceRequest Request;
typedef SpecialServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpecialService
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::SpecialService > {
  static const char* value()
  {
    return "966c6ddf09ea79b559b5427d5af8024f";
  }

  static const char* value(const ::wam_msgs::SpecialService&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::SpecialService > {
  static const char* value()
  {
    return "wam_msgs/SpecialService";
  }

  static const char* value(const ::wam_msgs::SpecialService&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::SpecialServiceRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::SpecialService > 
template<>
struct MD5Sum< ::wam_msgs::SpecialServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::SpecialService >::value();
  }
  static const char* value(const ::wam_msgs::SpecialServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::SpecialServiceRequest> should match 
// service_traits::DataType< ::wam_msgs::SpecialService > 
template<>
struct DataType< ::wam_msgs::SpecialServiceRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::SpecialService >::value();
  }
  static const char* value(const ::wam_msgs::SpecialServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::SpecialServiceResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::SpecialService > 
template<>
struct MD5Sum< ::wam_msgs::SpecialServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::SpecialService >::value();
  }
  static const char* value(const ::wam_msgs::SpecialServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::SpecialServiceResponse> should match 
// service_traits::DataType< ::wam_msgs::SpecialService > 
template<>
struct DataType< ::wam_msgs::SpecialServiceResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::SpecialService >::value();
  }
  static const char* value(const ::wam_msgs::SpecialServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_SPECIALSERVICE_H
