/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/robot/catkin_ws/src/wam_common/wam_msgs/srv/SpecialService.srv
 *
 */


#ifndef WAM_MSGS_MESSAGE_SPECIALSERVICERESPONSE_H
#define WAM_MSGS_MESSAGE_SPECIALSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_msgs
{
template <class ContainerAllocator>
struct SpecialServiceResponse_
{
  typedef SpecialServiceResponse_<ContainerAllocator> Type;

  SpecialServiceResponse_()
    : success(0)
    , response(0.0)
    , status()
    , bt()  {
    }
  SpecialServiceResponse_(const ContainerAllocator& _alloc)
    : success(0)
    , response(0.0)
    , status(_alloc)
    , bt(_alloc)  {
    }



   typedef int32_t _success_type;
  _success_type success;

   typedef double _response_type;
  _response_type response;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _bt_type;
  _bt_type bt;




  typedef boost::shared_ptr< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SpecialServiceResponse_

typedef ::wam_msgs::SpecialServiceResponse_<std::allocator<void> > SpecialServiceResponse;

typedef boost::shared_ptr< ::wam_msgs::SpecialServiceResponse > SpecialServiceResponsePtr;
typedef boost::shared_ptr< ::wam_msgs::SpecialServiceResponse const> SpecialServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/hydro/share/trajectory_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'wam_msgs': ['/home/robot/catkin_ws/src/wam_common/wam_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afdb7557c56a4609806fd9fcd3cc60b8";
  }

  static const char* value(const ::wam_msgs::SpecialServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xafdb7557c56a4609ULL;
  static const uint64_t static_value2 = 0x806fd9fcd3cc60b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_msgs/SpecialServiceResponse";
  }

  static const char* value(const ::wam_msgs::SpecialServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 success\n\
float64 response\n\
string status\n\
int32[] bt\n\
";
  }

  static const char* value(const ::wam_msgs::SpecialServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.response);
      stream.next(m.status);
      stream.next(m.bt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SpecialServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_msgs::SpecialServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_msgs::SpecialServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<int32_t>::stream(s, indent + "  ", v.success);
    s << indent << "response: ";
    Printer<double>::stream(s, indent + "  ", v.response);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "bt[]" << std::endl;
    for (size_t i = 0; i < v.bt.size(); ++i)
    {
      s << indent << "  bt[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.bt[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_MSGS_MESSAGE_SPECIALSERVICERESPONSE_H
